package app.denhan.model.jobs

data class Maintenance(
    val account: Account,
    val account_id: Int,
    val agent_id: Int,
    val assigned_to: Int,
    val assigned_to_type: String,
    val cancelled_date: Any,
    val cancelled_reason: Any,
    val comments: Any,
    val completed_date: Any,
    val created_date: String,
    val detail_note: String,
    val f_created_date: String,
    val f_created_time: String,
    val id: Int,
    val maintenance_instructions: List<MaintenanceInstruction>,
    val maintenance_jobs: List<MaintenanceJob>,
    val modified_date: String,
    val `property`: Property,
    val property_id: Int,
    val repair_code: String,
    val reported_by: String,
    val reporter_mobile: String,
    val reporter_name: String,
    val responsiblity: String,
    val show_completed_date: String,
    val sign: Any,
    val sign_path: String,
    val status: String,
    val t_created_date: Int,
    val tenant_request_id: Int,
    val time_in: Any,
    val time_out: Any,
    val total_time: Any
)